version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/eduardo/services/homeassistant:/config
    ports:
      - 8123:8123
      - 5683:5683
      - 4357:4357
      - 5683:5683/udp
    devices:
      - /dev/ttyUSB0
    restart: unless-stopped
